### ISSUE TITLE
this functionality is standard in 10.9

### ISSUE THREAD

**Issue by demianturner** [Abizern/JCSSheetController#1]
Hey Abizer, I guess you probably know this functionality is standard in 10.9?  I was unaware and spent some time integrating your component but will now be taking it out ;-) 

Might be worth mentioning on the intro page.

https://developer.apple.com/library/mac/releasenotes/AppKit/RN-AppKit/#//apple_ref/doc/uid/TP30000741-CH2-SW44

cheers Demian

**Comment by Abizern** [comment]
Thanks. I marked it as deprecated a while back.
